In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

In [3]:
# reading the data
path_file = "data.csv"
data = pd.read_csv(path_file)
data.head()
data.shape
data.dtypes # check all columns have expected data types


PERMNO      int64
DATE        int64
prc       float64
adjprc    float64
RET        object
VOL       float64
EXCHCD    float64
RET_DL    float64
dtype: object

In [4]:
# coerce RET to be numeric
data.RET = pd.to_numeric(data.RET, errors = "coerce")

# format date using pandas to_datetime() method
data.DATE = pd.to_datetime(data.DATE, format = "%Y%m%d")

# select only data from 1962 onwards
data = data[data.DATE.dt.year>=1962]


In [5]:
data

PERMNO       DATE      prc   adjprc       RET      VOL  EXCHCD   RET_DL
0   10000 1986-01-07   2.5625   2.5625       NaN   1000.0     3.0      NaN
1   10000 1986-01-08   2.5000   2.5000 -0.024390  12800.0     NaN -0.02439
2   10000 1986-01-09   2.5000   2.5000  0.000000   1400.0     NaN  0.00000
3   10000 1986-01-10   2.5000   2.5000  0.000000   8500.0     3.0  0.00000
4   10000 1986-01-13   2.6250   2.6250  0.050000   5450.0     NaN  0.05000
5   10001 1986-01-07  10.0000  10.0000  0.010000   5000.0     1.0      NaN
6   10001 1986-01-08  10.1000  10.1000  0.009901   6000.0     1.0  0.00990
7   10001 1986-01-09  10.2000  10.2000  0.009901   7000.0     1.0  0.00990

In [6]:
# data is in long format. Will create wide matrices with volumes and prices
vol = data.pivot(index="DATE", columns="PERMNO", values="VOL")
ret = data.pivot(index="DATE", columns="PERMNO", values="RET")


In [9]:
# remove possible nonsensical returns
ret[ret<-1] = -1
ret.head()

# unique dates
dates = vol.index
total_days = len(dates)
total_days


5

In [19]:
ret

PERMNO        10000     10001
DATE                         
1986-01-07  0.00000  0.000000
1986-01-08 -0.02439  0.009901
1986-01-09  0.00000  0.009901
1986-01-10  0.00000       NaN
1986-01-13  0.05000       NaN

In [17]:
prc = (ret + 1.).cumprod()

In [18]:
prc

PERMNO        10000     10001
DATE                         
1986-01-07  1.00000  1.000000
1986-01-08  0.97561  1.009901
1986-01-09  0.97561  1.019900
1986-01-10  0.97561       NaN
1986-01-13  1.02439       NaN

In [26]:
prc = prc.dropna()


In [27]:
prc.transpose()

DATE    1986-01-07  1986-01-08  1986-01-09
PERMNO                                    
10000          1.0    0.975610     0.97561
10001          1.0    1.009901     1.01990

In [24]:
from sklearn.metrics import pairwise_distances
import itertools

In [28]:
pairwise_distances(prc.transpose(), prc.transpose())

array([[0.        , 0.05601321],
       [0.05601321, 0.        ]])

In [29]:
pairwise_distances(prc.transpose())

array([[0.        , 0.05601321],
       [0.05601321, 0.        ]])

In [31]:
np.triu_indices(2, k=1)

(array([0]), array([1]))

In [37]:
ret

PERMNO        10000     10001
DATE                         
1986-01-07  0.00000  0.000000
1986-01-08 -0.02439  0.009901
1986-01-09  0.00000  0.009901
1986-01-10  0.00000       NaN
1986-01-13  0.05000       NaN

In [38]:
ret.shape[1]

2